- type: web
  name: production
  runtime: docker
  repo: https://github.com/gschool-blue-ocean/learnlaunchnexus.git
  plan: individual
  branch: production
  rootDit: learnlaunchnexus
  dockerCommand: docker compose up --build -f ./docker-compose.yml