- type: web
  name: production
  runtime: docker
  repo: https://github.com/gschool-blue-ocean/learnlaunchnexus
  plan: individual
  branch: production
  rootDir: learnlaunchnexus
  dockerCommand: docker compose up --build -f ./docker-compose.yml
